# Example Velocitytree project configuration
# Copy this file to .velocitytree.yaml and customize for your project

project:
  name: "My Awesome Project"
  version: "1.0.0"
  description: "A brief description of my project"

flatten:
  default_output: "context.md"
  default_format: "markdown"
  exclude_patterns:
    - "*.log"
    - "__pycache__"
    - ".git"
    - "node_modules"
    - "venv"
    - ".env"
    - "dist"
    - "build"
  include_patterns:
    - "*.py"
    - "*.js"
    - "*.ts"
    - "*.md"
    - "*.yaml"
    - "*.yml"
    - "*.json"

ai:
  default_model: "gpt-4"
  max_tokens: 4000
  temperature: 0.7
  # Add your API keys in environment variables:
  # OPENAI_API_KEY=your_key_here
  # ANTHROPIC_API_KEY=your_key_here

workflows:
  directory: ".velocitytree/workflows"
  custom_commands:
    - name: "test"
      description: "Run all tests"
      steps:
        - command: "pytest"
          name: "Run pytest"
    - name: "lint"
      description: "Run linters"
      steps:
        - command: "flake8 ."
          name: "Run flake8"
        - command: "black --check ."
          name: "Check black formatting"

plugins:
  enabled:
    - "json_formatter"
    - "output_validator"
  directories:
    - "./custom_plugins"

logging:
  level: "INFO"
  file: ".velocitytree/logs/velocitytree.log"