"""
Constants and default values for Velocitytree.
"""

# Default patterns based on TreeTamer
DEFAULT_EXCLUDE_PATTERNS = [
    "node_modules",
    ".git",
    ".idea",
    "__pycache__",
    "*.pyc",
    "*.pyo",
    "*.pyd",
    ".Python",
    "build/",
    "develop-eggs/",
    "dist/",
    "downloads/",
    "eggs/",
    ".eggs/",
    "lib/",
    "lib64/",
    "parts/",
    "sdist/",
    "var/",
    "wheels/",
    "*.egg-info/",
    ".installed.cfg",
    "*.egg",
    "MANIFEST",
    ".env",
    ".venv",
    "env/",
    "venv/",
    "ENV/",
    "env.bak/",
    "venv.bak/",
    "target/",
    "Cargo.lock",
    ".mypy_cache/",
    ".pytest_cache/",
    ".hypothesis/",
    "htmlcov/",
    ".tox/",
    ".coverage",
    ".coverage.*",
    ".cache",
    "nosetests.xml",
    "coverage.xml",
    "*.cover",
    ".hypothesis/",
    ".DS_Store",
    "Thumbs.db",
    ".vscode/",
    "*.swp",
    "*.swo",
    "*~",
    "vendor/",
    "logs/",
    "temp/",
    "tmp/",
    "cache/",
]

# Default file extensions to include
DEFAULT_INCLUDE_EXTENSIONS = [
    ".py",
    ".js",
    ".ts",
    ".jsx",
    ".tsx",
    ".java",
    ".cpp",
    ".c",
    ".h",
    ".hpp",
    ".cs",
    ".go",
    ".rs",
    ".rb",
    ".php",
    ".swift",
    ".kt",
    ".scala",
    ".r",
    ".m",
    ".mm",
    ".md",
    ".txt",
    ".rst",
    ".json",
    ".yaml",
    ".yml",
    ".toml",
    ".ini",
    ".cfg",
    ".conf",
    ".xml",
    ".html",
    ".css",
    ".scss",
    ".sass",
    ".less",
    ".vue",
    ".svelte",
    ".sql",
    ".sh",
    ".bash",
    ".zsh",
    ".fish",
    ".ps1",
    ".bat",
    ".cmd",
    "Dockerfile",
    "Makefile",
    "Rakefile",
    ".gitignore",
    ".dockerignore",
    "package.json",
    "requirements.txt",
    "Cargo.toml",
    "go.mod",
    "pom.xml",
    "build.gradle",
    "CMakeLists.txt",
]

# Default directories to exclude (from TreeTamer)
DEFAULT_EXCLUDE_DIRS = [
    "node_modules",
    "vendor",
    "target",
    ".git",
    ".idea",
    "build",
    "dist",
    "venv",
    "__pycache__",
    "coverage",
    "test-results",
    ".nyc_output",
    "junit",
    ".gradle",
    ".m2",
    "pkg",
    "bin",
    "obj",
    "out",
    ".next",
    ".nuxt",
    ".cache",
    "public/build",
    "android/build",
    "ios/build",
    "DerivedData",
    "Pods",
    ".terraform",
    ".serverless",
    ".webpack",
    "bazel-out",
    "buck-out",
]

# Binary file extensions to skip
DEFAULT_BINARY_EXTENSIONS = [
    ".exe",
    ".dll",
    ".so",
    ".dylib",
    ".o",
    ".a",
    ".lib",
    ".obj",
    ".pyc",
    ".pyo",
    ".pyd",
    ".class",
    ".jar",
    ".war",
    ".ear",
    ".zip",
    ".tar",
    ".gz",
    ".bz2",
    ".7z",
    ".rar",
    ".pdf",
    ".doc",
    ".docx",
    ".xls",
    ".xlsx",
    ".ppt",
    ".pptx",
    ".odt",
    ".ods",
    ".odp",
    ".png",
    ".jpg",
    ".jpeg",
    ".gif",
    ".bmp",
    ".ico",
    ".tiff",
    ".svg",
    ".webp",
    ".mp3",
    ".mp4",
    ".avi",
    ".mov",
    ".wmv",
    ".flv",
    ".mkv",
    ".webm",
    ".m4a",
    ".flac",
    ".wav",
    ".ogg",
    ".ttf",
    ".otf",
    ".woff",
    ".woff2",
    ".eot",
    ".db",
    ".sqlite",
    ".sqlite3",
]

# Project-specific files to always include (from TreeTamer)
PROJECT_FILES = [
    ".gitignore",
    "package.json",
    "package-lock.json",
    "requirements.txt",
    "setup.py",
    "setup.cfg",
    "pyproject.toml",
    "Cargo.toml",
    "go.mod",
    "go.sum",
    "pom.xml",
    "build.gradle",
    "build.gradle.kts",
    "settings.gradle",
    "settings.gradle.kts",
    "Gemfile",
    "Gemfile.lock",
    "composer.json",
    "composer.lock",
    "yarn.lock",
    "pnpm-lock.yaml",
    "Makefile",
    "Dockerfile",
    "docker-compose.yml",
    "docker-compose.yaml",
    ".env.example",
    ".env.template",
    "README.md",
    "README.rst",
    "README.txt",
    "LICENSE",
    "LICENSE.txt",
    "LICENSE.md",
    "CHANGELOG.md",
    "CHANGELOG.rst",
    "CONTRIBUTING.md",
    "CONTRIBUTING.rst",
    ".editorconfig",
    ".prettierrc",
    ".prettierrc.json",
    ".prettierrc.js",
    ".eslintrc",
    ".eslintrc.json",
    ".eslintrc.js",
    "tsconfig.json",
    "jsconfig.json",
    "jest.config.js",
    "webpack.config.js",
    "rollup.config.js",
    "vite.config.js",
    ".babelrc",
    ".browserslistrc",
    "angular.json",
    "nx.json",
    "workspace.json",
]

# AI providers
AI_PROVIDERS = {
    "openai": {
        "models": ["gpt-4", "gpt-3.5-turbo", "gpt-4-32k"],
        "default_model": "gpt-4",
        "api_key_env": "OPENAI_API_KEY",
    },
    "anthropic": {
        "models": ["claude-3-sonnet", "claude-3-opus", "claude-3-haiku"],
        "default_model": "claude-3-sonnet",
        "api_key_env": "ANTHROPIC_API_KEY",
    },
    "local": {
        "models": ["llama2", "codellama", "mistral"],
        "default_model": "codellama",
        "api_key_env": None,
    },
}

# Configuration file names
CONFIG_FILES = [
    ".velocitytree.yaml",
    ".velocitytree.yml",
    ".velocitytree.toml",
    "velocitytree.yaml",
    "velocitytree.yml",
    "velocitytree.toml",
    ".vtree.yaml",
    ".vtree.yml",
    ".vtree.toml",
]

# Default configuration
DEFAULT_CONFIG = {
    "project": {
        "name": "My Project",
        "version": "0.1.0",
    },
    "flatten": {
        "output_dir": "tamed_tree",
        "exclude": DEFAULT_EXCLUDE_PATTERNS[:10],  # Use first 10 as defaults
        "include_extensions": DEFAULT_INCLUDE_EXTENSIONS[:20],  # Use first 20 as defaults
        "preserve_structure": False,
        "follow_symlinks": False,
    },
    "ai": {
        "provider": "openai",
        "model": "gpt-4",
        "temperature": 0.7,
        "max_tokens": 2000,
    },
    "workflows": {},
    "plugins": [],
    "logging": {
        "level": "INFO",
        "format": "%(asctime)s - %(name)s - %(levelname)s - %(message)s",
    },
}